development:
  clients:
    default:
      database: mongoid_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: mongoid_test
      hosts:
        # - 18.191.227.19:27017
        #- 18.219.120.204:16082
         - localhost:27017
  options:
    raise_not_found_error: false

production:

  max_retries_on_connection_failure: 20
  persist_in_safe_mode: true
  skip_version_check: true
  default:
    database: twitter_production
    hosts:
      -  <%= ENV['MONGODB_URI'] || ENV['MONGOHQ_URL'] || ENV['MONGO_URL'] || ENV['MONGOLAB_URI'] %>
  
  options:
    raise_not_found_error: false
