development:
  clients:
    default:
      database: mongoid_development
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: mongoid_test
      hosts:
        - localhost:27017
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      database: mongoid_production
      hosts:
        <%= ENV['MONGODB_URI'] || ENV['MONGOHQ_URL'] || ENV['MONGO_URL'] || ENV['MONGOLAB_URI'] %>

  options:
    raise_not_found_error: false
